# Generated by Django 6.0.7 on 2026-07-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='insurance/')),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insurance Partner',
                'verbose_name_plural': 'Insurance Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcceptedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=150)),
                ('coverage_details', models.TextField(help_text='Short summary of what this plan covers.')),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insurancepartner')),
            ],
            options={
                'verbose_name': 'Accepted Plan',
                'verbose_name_plural': 'Accepted Plans',
                'ordering': ['partner__name', 'plan_name'],
            },
        ),
    ]
