# Generated by Django 6.0.7 on 2026-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('image', models.ImageField(upload_to='services/')),
                ('icon', models.CharField(choices=[('cleaning', 'Teeth Cleaning'), ('implant', 'Dental Implants'), ('root_canal', 'Root Canal'), ('braces', 'Braces'), ('whitening', 'Teeth Whitening'), ('cosmetic', 'Cosmetic Dentistry'), ('emergency', 'Emergency Care'), ('pediatric', 'Pediatric Dentistry'), ('surgery', 'Oral Surgery')], default='cleaning', max_length=20)),
                ('short_description', models.CharField(help_text='One-line summary shown on service cards.', max_length=255)),
                ('full_description', models.TextField(help_text='Detailed description shown on the service detail page.')),
                ('benefits', models.TextField(help_text='One benefit per line. Will be displayed as a bullet list.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Demo price in USD, e.g. 150.00', max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Typical appointment duration in minutes.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
    ]
