# Generated by Django 6.0.7 on 2026-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('photo', models.ImageField(upload_to='doctors/')),
                ('specialization', models.CharField(max_length=150)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('education', models.CharField(help_text="e.g. 'DDS, Harvard School of Dental Medicine'", max_length=255)),
                ('languages', models.CharField(help_text="Comma-separated, e.g. 'English, Spanish'", max_length=255)),
                ('biography', models.TextField()),
                ('working_hours', models.CharField(help_text="e.g. 'Mon - Fri: 9:00 AM - 5:00 PM'", max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
